"""Data models for the resignation scenario workflow."""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class ScenarioRole(StrEnum):
    """Scenario actor roles derived from trusted event sources."""

    EMPLOYEE = "employee"
    HR = "hr"
    TL = "tl"
    OPS = "ops"
    ADMIN = "admin"
    SYSTEM = "system"


class CasePhase(StrEnum):
    """Main state-machine phase for an active case."""

    AWAITING_HR_CONFIRM = "awaiting_hr_confirm"
    HANDOVER_AND_RECOVERY = "handover_and_recovery"
    AWAITING_HR_SIGNOFF = "awaiting_hr_signoff"
    CLOSED = "closed"


class CaseStatus(StrEnum):
    """Lifecycle status independent of escalation markers."""

    ACTIVE = "active"
    CLOSED = "closed"


class StepStatus(StrEnum):
    """Step status used inside the case payload."""

    WAITING = "waiting"
    ACTIVE = "active"
    DONE = "done"


class TaskType(StrEnum):
    """Tasks completed through the complete_task action."""

    HR_CONFIRM = "hr_confirm"
    TL_DONE = "tl_done"
    OPS_DONE = "ops_done"
    HR_SIGN = "hr_sign"


class NotificationIntent(BaseModel):
    """A role-targeted notification generated by the engine."""

    target_role: ScenarioRole
    content: str


class AuditEntry(BaseModel):
    """Append-only business audit entry."""

    ts: int
    actor_role: ScenarioRole
    source: str
    event: str
    data: dict[str, Any] = Field(default_factory=dict)


class Step1(BaseModel):
    """Step 1: receive resignation intent."""

    status: StepStatus = StepStatus.DONE
    completed_at: int


class Step2(BaseModel):
    """Step 2: HR confirmation."""

    status: StepStatus = StepStatus.ACTIVE
    deadline: int
    hr_confirmed: bool = False
    last_working_day: str | None = None
    completed_at: int | None = None


class Step3(BaseModel):
    """Step 3: handover and recovery in parallel."""

    status: StepStatus = StepStatus.WAITING
    deadline: int | None = None
    tl_done: bool = False
    tl_summary: str | None = None
    tl_completed_at: int | None = None
    tl_reminder_count: int = 0
    tl_last_reminded_at: int | None = None
    tl_escalated: bool = False
    ops_done: bool = False
    ops_recovery_data: dict[str, Any] = Field(default_factory=dict)
    ops_completed_at: int | None = None
    ops_reminder_count: int = 0
    ops_last_reminded_at: int | None = None
    ops_escalated: bool = False
    completed_at: int | None = None


class Step4(BaseModel):
    """Step 4: HR signoff and closure."""

    status: StepStatus = StepStatus.WAITING
    hr_signed: bool = False
    completed_at: int | None = None


class CaseSteps(BaseModel):
    """All workflow steps."""

    step_1: Step1
    step_2: Step2
    step_3: Step3
    step_4: Step4


class PendingIntent(BaseModel):
    """Pre-case resignation intent confirmation state."""

    detected_at: int
    expires_at: int


class ScenarioRegistry(BaseModel):
    """Global scenario registry outside any one case."""

    pending_intents: dict[str, PendingIntent] = Field(default_factory=dict)
    role_sources: dict[str, list[str]] = Field(default_factory=dict)


class ScenarioCase(BaseModel):
    """Persistent case state."""

    case_id: str
    phase: CasePhase
    status: CaseStatus
    escalated: bool = False
    escalations: list[str] = Field(default_factory=list)
    created_at: int
    employee: dict[str, Any]
    responsible: dict[str, dict[str, Any]] = Field(default_factory=dict)
    role_sources: dict[str, list[str]] = Field(default_factory=dict)
    steps: CaseSteps
    audit_log: list[AuditEntry] = Field(default_factory=list)


class ScenarioResult(BaseModel):
    """Structured result returned by the scenario orchestrator."""

    ok: bool
    code: str
    message: str
    case_id: str | None = None
    view: dict[str, Any] = Field(default_factory=dict)
    notifications: list[NotificationIntent] = Field(default_factory=list)
    archive_payload: dict[str, Any] | None = None
    errors: list[str] = Field(default_factory=list)
